### ISSUE TITLE
Multi-tenant sign-in

### ISSUE THREAD

**Issue by nmwur** [RichardJamesLopez/app-nesting#18]
- v1 for email 
- v2 for completing web3 modalities

**Comment by nmwur** [comment]
- google and discord auth - https://github.com/nmwur/app-nesting/commit/bea789d29335a8dfc381f030be8d68f62ac2109a
- web3 wallet connection - https://github.com/nmwur/app-nesting/commit/73a64e3b014a9577ec4b2540f65ff71912758738



![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/180a9ae4-7117-4861-813a-f7839954a77e)

**Comment by nmwur** [comment]
next:
- integrate authentication providers under a single user account
- styling

**Comment by nmwur** [comment]
mocked the invites ui:

- ![image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/f5ce64ac-48bd-415a-a5e6-4c4f5fa5d408)

- ![image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/4481f1f3-da53-42a3-b3a0-663c061e4e32)

- ![image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/42ffe017-4ca7-4117-b935-e562b5b95e95)

**Comment by RichardJamesLopez** [comment]
Awesome. 

> mocked the invites ui:

Just to clarify if user (specifically Inviter) sets max number of users to 25, then that means that up to 25 different logins can be created and have access to the Members list?

**Comment by nmwur** [comment]
yes

**Comment by RichardJamesLopez** [comment]
Adding specific sub-tasks as per the Figma [file](https://www.figma.com/design/xNyJM6MoO6amV9xoEVZczH/Prototype-specs-and-PRD?node-id=574%3A1452&t=ra2ejkqNCAraWiqu-1): 
- [ ] Test different users with different API access
- [ ] Create a separate “Customer” that has access to a different set of APIs
- [ ] Test transfer of user from Admin to Member and back

**Comment by nmwur** [comment]
1.
>Test different users with different API access (NOT different DB access; separate issue)
 Create a separate “Customer” that has access to a different set of APIs

can a Customer have more than one api access (e.g. to two notion tables and one hubspot table)?

---

2.
>Test transfer of user from Admin to Member (by accident). Can the remaining or newly assigned Admin turn me (currently Member) back to admin

should only the higher roles be able to manage the lower roles? for example, a user could be transferred from/to Admin only by the Owner and not by another Admin.
that's how discord handles it, should we do it similarly?

**Comment by RichardJamesLopez** [comment]
> should only the higher roles be able to manage the lower roles? for example, a user could be transferred from/to Admin only by the Owner and not by another Admin.
> that's how discord handles it, should we do it similarly?

Yes, let's default to this.

**Comment by RichardJamesLopez** [comment]
> > Test different users with different API access (NOT different DB access; separate issue)
> > Create a separate “Customer” that has access to a different set of APIs
> 
> can a Customer have more than one api access (e.g. to two notion tables and one hubspot table)?

Looks like we are discussing the same phenonomen here: https://github.com/users/RichardJamesLopez/projects/1?pane=issue&itemId=64163141

I think a customer having access to more than 1 type of API access is a good solution, but I think we need to outline the pros/cons of whether we should or shouldn't do that.

**Comment by nmwur** [comment]
true, i think we could narrow this task down to:

- sign-in via google
- role-based user management
  - promote/demote admins
  - kick members
- invites (except #28)

the items above seem to be done:
![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/5d61dfbd-f610-4d87-8aa8-e3ee617c8fc2)
