### ISSUE TITLE
Custom Rules page

### ISSUE THREAD

**Issue by nmwur** [RichardJamesLopez/app-nesting#19]
Build specific page within Admin panel for setting different rules for different fields

**Comment by RichardJamesLopez** [comment]
This is an mockup of the functionality from this [file](https://www.figma.com/design/cTbnjNQcLU0jg6csbqrf1k/Ourmada-Dashboard---PNF?node-id=0%3A1&t=jvXWD03FkxJJ16dv-1):


![Image](https://github.com/RichardJamesLopez/app-nesting/assets/8483531/a6ab89ee-97e1-4219-8a17-a25d28aa7011)

**Comment by nmwur** [comment]
should this table be read-only?

**Comment by RichardJamesLopez** [comment]
This table should be: 
- read only for members
- read-write for admins

**Comment by nmwur** [comment]
update:

- moved the column configuration card to the settings page
- hardcoded the "Deal Name" column (instead of "id"; it makes sense to me now)
- removed the "System columns" section (_doing things that don't scale_)

todo:

- [ ] rate the columns
- [ ] add formatting options (date, currency, etc)
- [ ] store configuration in database

![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/aad5fa1d-d170-4806-8486-e206e1cdc595)

**Comment by nmwur** [comment]
upd:
- store configuration in database (in progress)

**Comment by nmwur** [comment]
upd:
- fetch activities' columns based on database configuration records

todo:

- [ ] enable updating configuration

**Comment by nmwur** [comment]
upd:

- added column formatting in Settings
- applied column order and formatting to Pipeline
- enabled asynchronous sorting in Settings for value discovery

todo:

- [ ] rate the api fields


![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/bb90f651-89a7-40fc-8ae8-a66e9e2a7840)

**Comment by RichardJamesLopez** [comment]
Is there a way that the imported data from the column would auto-detect the data type? 

What happens if the user sets it to be something different than what it is imported in as? i.e. There is data that is imported as a `string` for a column titled "last updated", and then the user in Ourmada changes the data type to `date`. Will the values still come through and be mapped properly?

**Comment by nmwur** [comment]
yes, i think it's a good idea, we could use an LLM api for auto-detecting the data type.

if the user sets the data type to be something different than what is imported, it would generally show something like `NaN` or `Invalid Date` in the Preview.
in the given example with the "last updated" column, it would still return a formatted date because the value can be parsed as a date
