### ISSUE TITLE
Activity (Formerly Data Tab) expansion

### ISSUE THREAD

**Issue by RichardJamesLopez** [RichardJamesLopez/app-nesting#21]
- [x] Add commentary thread fields for each data. 
- [x] Store it to DB
- [x] Add user attribution to each data entry

Expand capabilities of featured page below in prototype

![Image](https://github.com/RichardJamesLopez/app-nesting/assets/8483531/a5d823ef-09c1-4a8e-8be1-825bf3c1baba)

**Comment by nmwur** [comment]
enabled comments functionality. what's left for them:
- [ ] improve performance
- [ ] add sorting by time/popularity

**Comment by RichardJamesLopez** [comment]
FYI - just checked the following as done: 

>  Add commentary thread fields for each data.
>  Store it to DB
>  Add user attribution to each data entry

**Comment by nmwur** [comment]
finishing commentary thread

**Comment by RichardJamesLopez** [comment]
Copying over the Goal of this ticket from Figma: 


![Image](https://github.com/RichardJamesLopez/app-nesting/assets/8483531/f923915a-a672-4b89-bc4d-8b09b81285db)
