### ISSUE TITLE
Pipeline Tab API integration - Notion

### ISSUE THREAD

**Issue by RichardJamesLopez** [RichardJamesLopez/app-nesting#23]
- [x] Populate table with data from Notion API
- [ ] Refine logic on custom visibility of data
- [ ] Prep each data point for individual page view that feed into [Issue #21](https://github.com/users/RichardJamesLopez/projects/1/views/1?pane=issue&itemId=63015593)

**Comment by RichardJamesLopez** [comment]
For additional context and a reply to an earlier Discord message

Re: 

> and prepared the ui for the alternative notion api. if the columns are unchanged, it should work.
> to add the api secret, you can either pass it on here or edit as the environment variables on vercel:
> https://vercel.com/richardjameslopez-s-team/app-nesting/settings/environment-variables
> NOTION_TOKEN_1 (the secret itself)
> NOTION_DB_ID_1 (the first path segment of the notion table url... or the whole url, and i'll then amend it)

- The notion APIs should correspond to different customers who will have different tables (or databases really). 
- Each of the columns will likely have different names (and subject to change at any point)
- This will be probably require an initial hardcoding for new customers during onboarding
   - ideally there would be a long term solution where Ourmada could be responsive to different column names on Notion, but that can be a seperate issue

Most notably this new NOTION_TOKEN_2(distinct from NOTION_TOKEN_1) will be for a marketing database, which may have different user behavior.

**Comment by RichardJamesLopez** [comment]
Would this suggestion

> i think a balanced solution for now is storing notion api keys in an encrypted column in the vercel database.

mean that each users (or organization) have access to all API tokens that Ourmada hosts? Or would it be limited to the API keys that are permisioned per user? 

For example, say we have 10 different customers, and 14 different API keys (say 8 of them have a single key, 1 of them has two keys, and the last one has five different keys). Would the last user have stored access to the five different keys, or all fourteen?

**Comment by nmwur** [comment]
access would be limited per organization.
should we also be able to limit access per user in the organization?

**Comment by RichardJamesLopez** [comment]
> should we also be able to limit access per user in the organization?

The answer of this depends on whether 
a) an API key have multiple databases (or tables), or  
b) it is one key per database

I am pretty sure it is `a)` so I think every user would get access to the same API Key (Notion one for example). Eventually we want to build capability to have `admin` user choose which databases each `member` user would have access to. 


Additionally, 

> access would be limited per organization.

I think we need to clarify if `organization` means each paying customer, or a specific sub-group for individual customers can assign. 

I have been anchoring to former, but we should clarify this in any documentation we have.

**Comment by nmwur** [comment]
upd:

- enabled connecting to notion api (Activities table and Settings)

todo:

- [ ] Summary table
- [ ] individual deal's page
- [ ] visibility


![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/a9b18ddc-9c69-4e63-b5d0-23eb0c6ddea9)

**Comment by nmwur** [comment]
upd:

- [x] display user names instead of ids

below is the minimum required api configuration for user names to work: https://www.notion.so/profile/integrations

![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/9184d2be-5aa4-4ec4-92ee-513e3776b4fd)

---

todo:

- [ ] check formatted dates' time zone

**Comment by nmwur** [comment]
@RichardJamesLopez i think i've reproduced and fixed the bug
