### ISSUE TITLE
Comment others

### ISSUE THREAD

**Issue by RichardJamesLopez** [RichardJamesLopez/app-nesting#26]
- [ ]  One user able to comment in other user (Alice adds @Bob  in a comment) 
- [ ]  mentioned user receives a notification (in icon in top right hand corner of app
- [ ] (Optional)  mentioned user gets an email in addition to app notification
- [ ] Make these mentions appear in an activity feed (to be built or added to homepage soon)

**Comment by nmwur** [comment]
upd:
- added mentions ui
![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/e2953ea6-5643-4a27-8b3c-4e5deced3a6c)

todo:
- [ ] let previous comments in the database support mentions

**Comment by nmwur** [comment]
upd:
- added backend for mentions
- added notifications menu
<img width="338" alt="image" src="https://github.com/RichardJamesLopez/app-nesting/assets/22333399/a30cd130-eb2b-4918-a5f7-e5c9ec069f18">



todo:
- [ ] enable infinite scroll in notifications menu
- [ ] redirect the user to the comment from a notification

**Comment by nmwur** [comment]
the user gets redirected from a notification to the comment:
![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/9e3897f2-e45b-4722-9dd6-cdfd3dd8ba97)
