### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by nmwur** [RichardJamesLopez/app-nesting#39]

**Comment by RichardJamesLopez** [comment]
Takeaway: 
- let's turn on Vercel analytics, see how it looks 
- reassess when trial ends - then see if we want to migrate to Posthog, or keep vercel

**Comment by RichardJamesLopez** [comment]
Enabled Web Analytics services on our Vercel package. 

@nmwur - can you add the following 3 steps to the stage env before we push?  

1. Install  package `npm i @vercel/analytics`
2. Import and use the <Analytics/> React component into your app's layout. `import { Analytics } from "@vercel/analytics/react"`
3. Deploy changes and visit the deployment to collect page views.

If we don't see data after 30 seconds, please check for content blockers and try to navigate between pages on site. [Here](https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app) is the additional documentation.

**Comment by nmwur** [comment]
added those three steps, and the data is now showing in the stage environment.
it should also work in production after a PR this week
