### ISSUE TITLE
Support functionality

### ISSUE THREAD

**Issue by nmwur** [RichardJamesLopez/app-nesting#42]
Somewhere on app, there be a modal that opens up a support modal

**Comment by nmwur** [comment]
upd:




![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/b4453c3c-6067-4b47-a07f-756bd53affc5)


![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/7e289496-869c-4a49-8b62-36e780b29167)

**Comment by RichardJamesLopez** [comment]
When we receive this form, what will be the contents? Will it have PII or any email/account info?

**Comment by nmwur** [comment]
i just accidentally sent you a support request.
the contents include user name in the body and the email in the reply-to field
